# Generated by Django 4.1.7 on 2023-03-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteT',
            fields=[
                ('fname', models.CharField(db_column='Fname', max_length=30, primary_key=True, serialize=False)),
                ('lname', models.CharField(db_column='Lname', max_length=30)),
                ('dob', models.CharField(db_column='DOB', max_length=10)),
                ('sportsteam', models.CharField(blank=True, db_column='SportsTeam', max_length=30, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=15, null=True)),
                ('height', models.FloatField(blank=True, db_column='Height', null=True)),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
            ],
            options={
                'db_table': 'Athlete_T',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamT',
            fields=[
                ('sport', models.CharField(db_column='Sport', max_length=30, primary_key=True, serialize=False)),
                ('tname', models.CharField(db_column='Tname', max_length=30)),
            ],
            options={
                'db_table': 'Team_T',
                'managed': False,
            },
        ),
    ]
