# Generated by Django 4.1.7 on 2023-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessT',
            fields=[
                ('fname', models.CharField(db_column='Fname', max_length=30, primary_key=True, serialize=False)),
                ('lname', models.CharField(db_column='Lname', max_length=30)),
                ('dob', models.CharField(db_column='DOB', max_length=10)),
                ('status', models.CharField(db_column='Status', max_length=1)),
                ('sportsteam', models.CharField(blank=True, db_column='SportsTeam', max_length=30, null=True)),
                ('date', models.CharField(db_column='Date', max_length=10)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=30, null=True)),
                ('hoursofsleep', models.IntegerField(blank=True, db_column='HoursOfSleep', null=True)),
                ('sleepquality', models.IntegerField(blank=True, db_column='SleepQuality', null=True)),
                ('breakfast', models.IntegerField(blank=True, db_column='Breakfast', null=True)),
                ('hydration', models.IntegerField(blank=True, db_column='Hydration', null=True)),
                ('soreness', models.IntegerField(blank=True, db_column='Soreness', null=True)),
                ('stress', models.IntegerField(blank=True, db_column='Stress', null=True)),
                ('mood', models.IntegerField(blank=True, db_column='Mood', null=True)),
            ],
            options={
                'db_table': 'Wellness_T',
                'managed': False,
            },
        ),
    ]
