# Generated by Django 4.1.7 on 2023-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_wellnesst'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiT',
            fields=[
                ('fname', models.CharField(db_column='Fname', max_length=30, primary_key=True, serialize=False)),
                ('lname', models.CharField(db_column='Lname', max_length=30)),
                ('dob', models.CharField(db_column='DOB', max_length=10)),
                ('datekpi', models.CharField(db_column='DateKPI', max_length=10)),
                ('testtype', models.CharField(db_column='TestType', max_length=30)),
                ('testresult', models.FloatField(blank=True, db_column='TestResult', null=True)),
            ],
            options={
                'db_table': 'KPI_T',
                'managed': False,
            },
        ),
    ]
